//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("ChangingMajorsManagementSystemModel", "FK_SYSTEM_U_REFERENCE_SYSTEM_U", "system_user_manager", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ChangingMajors.DAL.Entity.system_user_manager), "System_User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ChangingMajors.DAL.Entity.System_User), true)]
[assembly: EdmRelationshipAttribute("ChangingMajorsManagementSystemModel", "FK_USER_ENT_REFERENCE_USER_CHA", "User_ChangingMajors_Start", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ChangingMajors.DAL.Entity.User_ChangingMajors_Start), "User_Entry", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ChangingMajors.DAL.Entity.User_Entry), true)]

#endregion

namespace ChangingMajors.DAL.Entity
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ChangingMajorsManagementSystemEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ChangingMajorsManagementSystemEntities”部分中的连接字符串初始化新 ChangingMajorsManagementSystemEntities 对象。
        /// </summary>
        public ChangingMajorsManagementSystemEntities() : base("name=ChangingMajorsManagementSystemEntities", "ChangingMajorsManagementSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ChangingMajorsManagementSystemEntities 对象。
        /// </summary>
        public ChangingMajorsManagementSystemEntities(string connectionString) : base(connectionString, "ChangingMajorsManagementSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ChangingMajorsManagementSystemEntities 对象。
        /// </summary>
        public ChangingMajorsManagementSystemEntities(EntityConnection connection) : base(connection, "ChangingMajorsManagementSystemEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<System_Majors> System_Majors
        {
            get
            {
                if ((_System_Majors == null))
                {
                    _System_Majors = base.CreateObjectSet<System_Majors>("System_Majors");
                }
                return _System_Majors;
            }
        }
        private ObjectSet<System_Majors> _System_Majors;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<System_User> System_User
        {
            get
            {
                if ((_System_User == null))
                {
                    _System_User = base.CreateObjectSet<System_User>("System_User");
                }
                return _System_User;
            }
        }
        private ObjectSet<System_User> _System_User;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<system_user_detail> system_user_detail
        {
            get
            {
                if ((_system_user_detail == null))
                {
                    _system_user_detail = base.CreateObjectSet<system_user_detail>("system_user_detail");
                }
                return _system_user_detail;
            }
        }
        private ObjectSet<system_user_detail> _system_user_detail;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<system_user_manager> system_user_manager
        {
            get
            {
                if ((_system_user_manager == null))
                {
                    _system_user_manager = base.CreateObjectSet<system_user_manager>("system_user_manager");
                }
                return _system_user_manager;
            }
        }
        private ObjectSet<system_user_manager> _system_user_manager;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<User_ChangingMajors_Start> User_ChangingMajors_Start
        {
            get
            {
                if ((_User_ChangingMajors_Start == null))
                {
                    _User_ChangingMajors_Start = base.CreateObjectSet<User_ChangingMajors_Start>("User_ChangingMajors_Start");
                }
                return _User_ChangingMajors_Start;
            }
        }
        private ObjectSet<User_ChangingMajors_Start> _User_ChangingMajors_Start;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<User_Entry> User_Entry
        {
            get
            {
                if ((_User_Entry == null))
                {
                    _User_Entry = base.CreateObjectSet<User_Entry>("User_Entry");
                }
                return _User_Entry;
            }
        }
        private ObjectSet<User_Entry> _User_Entry;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<User_Notice> User_Notice
        {
            get
            {
                if ((_User_Notice == null))
                {
                    _User_Notice = base.CreateObjectSet<User_Notice>("User_Notice");
                }
                return _User_Notice;
            }
        }
        private ObjectSet<User_Notice> _User_Notice;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 System_Majors EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSystem_Majors(System_Majors system_Majors)
        {
            base.AddObject("System_Majors", system_Majors);
        }
    
        /// <summary>
        /// 用于向 System_User EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSystem_User(System_User system_User)
        {
            base.AddObject("System_User", system_User);
        }
    
        /// <summary>
        /// 用于向 system_user_detail EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTosystem_user_detail(system_user_detail system_user_detail)
        {
            base.AddObject("system_user_detail", system_user_detail);
        }
    
        /// <summary>
        /// 用于向 system_user_manager EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTosystem_user_manager(system_user_manager system_user_manager)
        {
            base.AddObject("system_user_manager", system_user_manager);
        }
    
        /// <summary>
        /// 用于向 User_ChangingMajors_Start EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUser_ChangingMajors_Start(User_ChangingMajors_Start user_ChangingMajors_Start)
        {
            base.AddObject("User_ChangingMajors_Start", user_ChangingMajors_Start);
        }
    
        /// <summary>
        /// 用于向 User_Entry EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUser_Entry(User_Entry user_Entry)
        {
            base.AddObject("User_Entry", user_Entry);
        }
    
        /// <summary>
        /// 用于向 User_Notice EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUser_Notice(User_Notice user_Notice)
        {
            base.AddObject("User_Notice", user_Notice);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChangingMajorsManagementSystemModel", Name="System_Majors")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class System_Majors : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 System_Majors 对象。
        /// </summary>
        /// <param name="major_id">major_id 属性的初始值。</param>
        public static System_Majors CreateSystem_Majors(global::System.Int32 major_id)
        {
            System_Majors system_Majors = new System_Majors();
            system_Majors.major_id = major_id;
            return system_Majors;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 major_id
        {
            get
            {
                return _major_id;
            }
            set
            {
                if (_major_id != value)
                {
                    Onmajor_idChanging(value);
                    ReportPropertyChanging("major_id");
                    _major_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("major_id");
                    Onmajor_idChanged();
                }
            }
        }
        private global::System.Int32 _major_id;
        partial void Onmajor_idChanging(global::System.Int32 value);
        partial void Onmajor_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String major_name
        {
            get
            {
                return _major_name;
            }
            set
            {
                Onmajor_nameChanging(value);
                ReportPropertyChanging("major_name");
                _major_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("major_name");
                Onmajor_nameChanged();
            }
        }
        private global::System.String _major_name;
        partial void Onmajor_nameChanging(global::System.String value);
        partial void Onmajor_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> major_art_science
        {
            get
            {
                return _major_art_science;
            }
            set
            {
                Onmajor_art_scienceChanging(value);
                ReportPropertyChanging("major_art_science");
                _major_art_science = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("major_art_science");
                Onmajor_art_scienceChanged();
            }
        }
        private Nullable<global::System.Int32> _major_art_science;
        partial void Onmajor_art_scienceChanging(Nullable<global::System.Int32> value);
        partial void Onmajor_art_scienceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> major_flag
        {
            get
            {
                return _major_flag;
            }
            set
            {
                Onmajor_flagChanging(value);
                ReportPropertyChanging("major_flag");
                _major_flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("major_flag");
                Onmajor_flagChanged();
            }
        }
        private Nullable<global::System.Int32> _major_flag;
        partial void Onmajor_flagChanging(Nullable<global::System.Int32> value);
        partial void Onmajor_flagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String major_date
        {
            get
            {
                return _major_date;
            }
            set
            {
                Onmajor_dateChanging(value);
                ReportPropertyChanging("major_date");
                _major_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("major_date");
                Onmajor_dateChanged();
            }
        }
        private global::System.String _major_date;
        partial void Onmajor_dateChanging(global::System.String value);
        partial void Onmajor_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> major_num
        {
            get
            {
                return _major_num;
            }
            set
            {
                Onmajor_numChanging(value);
                ReportPropertyChanging("major_num");
                _major_num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("major_num");
                Onmajor_numChanged();
            }
        }
        private Nullable<global::System.Int32> _major_num;
        partial void Onmajor_numChanging(Nullable<global::System.Int32> value);
        partial void Onmajor_numChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> major_start_flag
        {
            get
            {
                return _major_start_flag;
            }
            set
            {
                Onmajor_start_flagChanging(value);
                ReportPropertyChanging("major_start_flag");
                _major_start_flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("major_start_flag");
                Onmajor_start_flagChanged();
            }
        }
        private Nullable<global::System.Int32> _major_start_flag;
        partial void Onmajor_start_flagChanging(Nullable<global::System.Int32> value);
        partial void Onmajor_start_flagChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChangingMajorsManagementSystemModel", Name="System_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class System_User : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 System_User 对象。
        /// </summary>
        /// <param name="user_id">user_id 属性的初始值。</param>
        public static System_User CreateSystem_User(global::System.Int32 user_id)
        {
            System_User system_User = new System_User();
            system_User.user_id = user_id;
            return system_User;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> upload_id
        {
            get
            {
                return _upload_id;
            }
            set
            {
                Onupload_idChanging(value);
                ReportPropertyChanging("upload_id");
                _upload_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("upload_id");
                Onupload_idChanged();
            }
        }
        private Nullable<global::System.Int32> _upload_id;
        partial void Onupload_idChanging(Nullable<global::System.Int32> value);
        partial void Onupload_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_num
        {
            get
            {
                return _user_num;
            }
            set
            {
                Onuser_numChanging(value);
                ReportPropertyChanging("user_num");
                _user_num = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_num");
                Onuser_numChanged();
            }
        }
        private global::System.String _user_num;
        partial void Onuser_numChanging(global::System.String value);
        partial void Onuser_numChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_password
        {
            get
            {
                return _user_password;
            }
            set
            {
                Onuser_passwordChanging(value);
                ReportPropertyChanging("user_password");
                _user_password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_password");
                Onuser_passwordChanged();
            }
        }
        private global::System.String _user_password;
        partial void Onuser_passwordChanging(global::System.String value);
        partial void Onuser_passwordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_name
        {
            get
            {
                return _user_name;
            }
            set
            {
                Onuser_nameChanging(value);
                ReportPropertyChanging("user_name");
                _user_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_name");
                Onuser_nameChanged();
            }
        }
        private global::System.String _user_name;
        partial void Onuser_nameChanging(global::System.String value);
        partial void Onuser_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_sex
        {
            get
            {
                return _user_sex;
            }
            set
            {
                Onuser_sexChanging(value);
                ReportPropertyChanging("user_sex");
                _user_sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_sex");
                Onuser_sexChanged();
            }
        }
        private Nullable<global::System.Int32> _user_sex;
        partial void Onuser_sexChanging(Nullable<global::System.Int32> value);
        partial void Onuser_sexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_class
        {
            get
            {
                return _user_class;
            }
            set
            {
                Onuser_classChanging(value);
                ReportPropertyChanging("user_class");
                _user_class = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_class");
                Onuser_classChanged();
            }
        }
        private global::System.String _user_class;
        partial void Onuser_classChanging(global::System.String value);
        partial void Onuser_classChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_arts_science
        {
            get
            {
                return _user_arts_science;
            }
            set
            {
                Onuser_arts_scienceChanging(value);
                ReportPropertyChanging("user_arts_science");
                _user_arts_science = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_arts_science");
                Onuser_arts_scienceChanged();
            }
        }
        private Nullable<global::System.Int32> _user_arts_science;
        partial void Onuser_arts_scienceChanging(Nullable<global::System.Int32> value);
        partial void Onuser_arts_scienceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_address
        {
            get
            {
                return _user_address;
            }
            set
            {
                Onuser_addressChanging(value);
                ReportPropertyChanging("user_address");
                _user_address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_address");
                Onuser_addressChanged();
            }
        }
        private global::System.String _user_address;
        partial void Onuser_addressChanging(global::System.String value);
        partial void Onuser_addressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_demotion
        {
            get
            {
                return _user_demotion;
            }
            set
            {
                Onuser_demotionChanging(value);
                ReportPropertyChanging("user_demotion");
                _user_demotion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_demotion");
                Onuser_demotionChanged();
            }
        }
        private Nullable<global::System.Int32> _user_demotion;
        partial void Onuser_demotionChanging(Nullable<global::System.Int32> value);
        partial void Onuser_demotionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_flied_class
        {
            get
            {
                return _user_flied_class;
            }
            set
            {
                Onuser_flied_classChanging(value);
                ReportPropertyChanging("user_flied_class");
                _user_flied_class = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_flied_class");
                Onuser_flied_classChanged();
            }
        }
        private Nullable<global::System.Int32> _user_flied_class;
        partial void Onuser_flied_classChanging(Nullable<global::System.Int32> value);
        partial void Onuser_flied_classChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_disciplinary_award
        {
            get
            {
                return _user_disciplinary_award;
            }
            set
            {
                Onuser_disciplinary_awardChanging(value);
                ReportPropertyChanging("user_disciplinary_award");
                _user_disciplinary_award = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_disciplinary_award");
                Onuser_disciplinary_awardChanged();
            }
        }
        private Nullable<global::System.Int32> _user_disciplinary_award;
        partial void Onuser_disciplinary_awardChanging(Nullable<global::System.Int32> value);
        partial void Onuser_disciplinary_awardChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_long_phone
        {
            get
            {
                return _user_long_phone;
            }
            set
            {
                Onuser_long_phoneChanging(value);
                ReportPropertyChanging("user_long_phone");
                _user_long_phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_long_phone");
                Onuser_long_phoneChanged();
            }
        }
        private global::System.String _user_long_phone;
        partial void Onuser_long_phoneChanging(global::System.String value);
        partial void Onuser_long_phoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_short_phone
        {
            get
            {
                return _user_short_phone;
            }
            set
            {
                Onuser_short_phoneChanging(value);
                ReportPropertyChanging("user_short_phone");
                _user_short_phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_short_phone");
                Onuser_short_phoneChanged();
            }
        }
        private global::System.String _user_short_phone;
        partial void Onuser_short_phoneChanging(global::System.String value);
        partial void Onuser_short_phoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_honour
        {
            get
            {
                return _user_honour;
            }
            set
            {
                Onuser_honourChanging(value);
                ReportPropertyChanging("user_honour");
                _user_honour = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_honour");
                Onuser_honourChanged();
            }
        }
        private global::System.String _user_honour;
        partial void Onuser_honourChanging(global::System.String value);
        partial void Onuser_honourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_power
        {
            get
            {
                return _user_power;
            }
            set
            {
                Onuser_powerChanging(value);
                ReportPropertyChanging("user_power");
                _user_power = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_power");
                Onuser_powerChanged();
            }
        }
        private Nullable<global::System.Int32> _user_power;
        partial void Onuser_powerChanging(Nullable<global::System.Int32> value);
        partial void Onuser_powerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_flag
        {
            get
            {
                return _user_flag;
            }
            set
            {
                Onuser_flagChanging(value);
                ReportPropertyChanging("user_flag");
                _user_flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_flag");
                Onuser_flagChanged();
            }
        }
        private Nullable<global::System.Int32> _user_flag;
        partial void Onuser_flagChanging(Nullable<global::System.Int32> value);
        partial void Onuser_flagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_date
        {
            get
            {
                return _user_date;
            }
            set
            {
                Onuser_dateChanging(value);
                ReportPropertyChanging("user_date");
                _user_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_date");
                Onuser_dateChanged();
            }
        }
        private global::System.String _user_date;
        partial void Onuser_dateChanging(global::System.String value);
        partial void Onuser_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> user_apply_flag
        {
            get
            {
                return _user_apply_flag;
            }
            set
            {
                Onuser_apply_flagChanging(value);
                ReportPropertyChanging("user_apply_flag");
                _user_apply_flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_apply_flag");
                Onuser_apply_flagChanged();
            }
        }
        private Nullable<global::System.Int32> _user_apply_flag;
        partial void Onuser_apply_flagChanging(Nullable<global::System.Int32> value);
        partial void Onuser_apply_flagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_email
        {
            get
            {
                return _user_email;
            }
            set
            {
                Onuser_emailChanging(value);
                ReportPropertyChanging("user_email");
                _user_email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_email");
                Onuser_emailChanged();
            }
        }
        private global::System.String _user_email;
        partial void Onuser_emailChanging(global::System.String value);
        partial void Onuser_emailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String major_name
        {
            get
            {
                return _major_name;
            }
            set
            {
                Onmajor_nameChanging(value);
                ReportPropertyChanging("major_name");
                _major_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("major_name");
                Onmajor_nameChanged();
            }
        }
        private global::System.String _major_name;
        partial void Onmajor_nameChanging(global::System.String value);
        partial void Onmajor_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sys_major_name
        {
            get
            {
                return _sys_major_name;
            }
            set
            {
                Onsys_major_nameChanging(value);
                ReportPropertyChanging("sys_major_name");
                _sys_major_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sys_major_name");
                Onsys_major_nameChanged();
            }
        }
        private global::System.String _sys_major_name;
        partial void Onsys_major_nameChanging(global::System.String value);
        partial void Onsys_major_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_major_id
        {
            get
            {
                return _user_major_id;
            }
            set
            {
                Onuser_major_idChanging(value);
                ReportPropertyChanging("user_major_id");
                _user_major_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_major_id");
                Onuser_major_idChanged();
            }
        }
        private global::System.String _user_major_id;
        partial void Onuser_major_idChanging(global::System.String value);
        partial void Onuser_major_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_sys_major_id
        {
            get
            {
                return _user_sys_major_id;
            }
            set
            {
                Onuser_sys_major_idChanging(value);
                ReportPropertyChanging("user_sys_major_id");
                _user_sys_major_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_sys_major_id");
                Onuser_sys_major_idChanged();
            }
        }
        private global::System.String _user_sys_major_id;
        partial void Onuser_sys_major_idChanging(global::System.String value);
        partial void Onuser_sys_major_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_english_level_four
        {
            get
            {
                return _user_english_level_four;
            }
            set
            {
                Onuser_english_level_fourChanging(value);
                ReportPropertyChanging("user_english_level_four");
                _user_english_level_four = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_english_level_four");
                Onuser_english_level_fourChanged();
            }
        }
        private global::System.String _user_english_level_four;
        partial void Onuser_english_level_fourChanging(global::System.String value);
        partial void Onuser_english_level_fourChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_english_level_six
        {
            get
            {
                return _user_english_level_six;
            }
            set
            {
                Onuser_english_level_sixChanging(value);
                ReportPropertyChanging("user_english_level_six");
                _user_english_level_six = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_english_level_six");
                Onuser_english_level_sixChanged();
            }
        }
        private global::System.String _user_english_level_six;
        partial void Onuser_english_level_sixChanging(global::System.String value);
        partial void Onuser_english_level_sixChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_last_major_num
        {
            get
            {
                return _user_last_major_num;
            }
            set
            {
                Onuser_last_major_numChanging(value);
                ReportPropertyChanging("user_last_major_num");
                _user_last_major_num = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_last_major_num");
                Onuser_last_major_numChanged();
            }
        }
        private global::System.String _user_last_major_num;
        partial void Onuser_last_major_numChanging(global::System.String value);
        partial void Onuser_last_major_numChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_credit_weighted_average
        {
            get
            {
                return _user_credit_weighted_average;
            }
            set
            {
                Onuser_credit_weighted_averageChanging(value);
                ReportPropertyChanging("user_credit_weighted_average");
                _user_credit_weighted_average = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_credit_weighted_average");
                Onuser_credit_weighted_averageChanged();
            }
        }
        private global::System.String _user_credit_weighted_average;
        partial void Onuser_credit_weighted_averageChanging(global::System.String value);
        partial void Onuser_credit_weighted_averageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_major_ranking
        {
            get
            {
                return _user_major_ranking;
            }
            set
            {
                Onuser_major_rankingChanging(value);
                ReportPropertyChanging("user_major_ranking");
                _user_major_ranking = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_major_ranking");
                Onuser_major_rankingChanged();
            }
        }
        private global::System.String _user_major_ranking;
        partial void Onuser_major_rankingChanging(global::System.String value);
        partial void Onuser_major_rankingChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ChangingMajorsManagementSystemModel", "FK_SYSTEM_U_REFERENCE_SYSTEM_U", "system_user_manager")]
        public system_user_manager system_user_manager
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<system_user_manager>("ChangingMajorsManagementSystemModel.FK_SYSTEM_U_REFERENCE_SYSTEM_U", "system_user_manager").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<system_user_manager>("ChangingMajorsManagementSystemModel.FK_SYSTEM_U_REFERENCE_SYSTEM_U", "system_user_manager").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<system_user_manager> system_user_managerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<system_user_manager>("ChangingMajorsManagementSystemModel.FK_SYSTEM_U_REFERENCE_SYSTEM_U", "system_user_manager");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<system_user_manager>("ChangingMajorsManagementSystemModel.FK_SYSTEM_U_REFERENCE_SYSTEM_U", "system_user_manager", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChangingMajorsManagementSystemModel", Name="system_user_detail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class system_user_detail : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 system_user_detail 对象。
        /// </summary>
        /// <param name="detail_id">detail_id 属性的初始值。</param>
        public static system_user_detail Createsystem_user_detail(global::System.Int32 detail_id)
        {
            system_user_detail system_user_detail = new system_user_detail();
            system_user_detail.detail_id = detail_id;
            return system_user_detail;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 detail_id
        {
            get
            {
                return _detail_id;
            }
            set
            {
                if (_detail_id != value)
                {
                    Ondetail_idChanging(value);
                    ReportPropertyChanging("detail_id");
                    _detail_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("detail_id");
                    Ondetail_idChanged();
                }
            }
        }
        private global::System.Int32 _detail_id;
        partial void Ondetail_idChanging(global::System.Int32 value);
        partial void Ondetail_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_num
        {
            get
            {
                return _user_num;
            }
            set
            {
                Onuser_numChanging(value);
                ReportPropertyChanging("user_num");
                _user_num = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_num");
                Onuser_numChanged();
            }
        }
        private global::System.String _user_num;
        partial void Onuser_numChanging(global::System.String value);
        partial void Onuser_numChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_major_ranking
        {
            get
            {
                return _user_major_ranking;
            }
            set
            {
                Onuser_major_rankingChanging(value);
                ReportPropertyChanging("user_major_ranking");
                _user_major_ranking = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_major_ranking");
                Onuser_major_rankingChanged();
            }
        }
        private global::System.String _user_major_ranking;
        partial void Onuser_major_rankingChanging(global::System.String value);
        partial void Onuser_major_rankingChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_major_num
        {
            get
            {
                return _user_major_num;
            }
            set
            {
                Onuser_major_numChanging(value);
                ReportPropertyChanging("user_major_num");
                _user_major_num = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_major_num");
                Onuser_major_numChanged();
            }
        }
        private global::System.String _user_major_num;
        partial void Onuser_major_numChanging(global::System.String value);
        partial void Onuser_major_numChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_credit_weighted_average
        {
            get
            {
                return _user_credit_weighted_average;
            }
            set
            {
                Onuser_credit_weighted_averageChanging(value);
                ReportPropertyChanging("user_credit_weighted_average");
                _user_credit_weighted_average = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_credit_weighted_average");
                Onuser_credit_weighted_averageChanged();
            }
        }
        private global::System.String _user_credit_weighted_average;
        partial void Onuser_credit_weighted_averageChanging(global::System.String value);
        partial void Onuser_credit_weighted_averageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String detail_date
        {
            get
            {
                return _detail_date;
            }
            set
            {
                Ondetail_dateChanging(value);
                ReportPropertyChanging("detail_date");
                _detail_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("detail_date");
                Ondetail_dateChanged();
            }
        }
        private global::System.String _detail_date;
        partial void Ondetail_dateChanging(global::System.String value);
        partial void Ondetail_dateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChangingMajorsManagementSystemModel", Name="system_user_manager")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class system_user_manager : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 system_user_manager 对象。
        /// </summary>
        /// <param name="upload_id">upload_id 属性的初始值。</param>
        public static system_user_manager Createsystem_user_manager(global::System.Int32 upload_id)
        {
            system_user_manager system_user_manager = new system_user_manager();
            system_user_manager.upload_id = upload_id;
            return system_user_manager;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 upload_id
        {
            get
            {
                return _upload_id;
            }
            set
            {
                if (_upload_id != value)
                {
                    Onupload_idChanging(value);
                    ReportPropertyChanging("upload_id");
                    _upload_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("upload_id");
                    Onupload_idChanged();
                }
            }
        }
        private global::System.Int32 _upload_id;
        partial void Onupload_idChanging(global::System.Int32 value);
        partial void Onupload_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String upload_date
        {
            get
            {
                return _upload_date;
            }
            set
            {
                Onupload_dateChanging(value);
                ReportPropertyChanging("upload_date");
                _upload_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("upload_date");
                Onupload_dateChanged();
            }
        }
        private global::System.String _upload_date;
        partial void Onupload_dateChanging(global::System.String value);
        partial void Onupload_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String upload_state
        {
            get
            {
                return _upload_state;
            }
            set
            {
                Onupload_stateChanging(value);
                ReportPropertyChanging("upload_state");
                _upload_state = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("upload_state");
                Onupload_stateChanged();
            }
        }
        private global::System.String _upload_state;
        partial void Onupload_stateChanging(global::System.String value);
        partial void Onupload_stateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String upload_num
        {
            get
            {
                return _upload_num;
            }
            set
            {
                Onupload_numChanging(value);
                ReportPropertyChanging("upload_num");
                _upload_num = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("upload_num");
                Onupload_numChanged();
            }
        }
        private global::System.String _upload_num;
        partial void Onupload_numChanging(global::System.String value);
        partial void Onupload_numChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ChangingMajorsManagementSystemModel", "FK_SYSTEM_U_REFERENCE_SYSTEM_U", "System_User")]
        public EntityCollection<System_User> System_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<System_User>("ChangingMajorsManagementSystemModel.FK_SYSTEM_U_REFERENCE_SYSTEM_U", "System_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<System_User>("ChangingMajorsManagementSystemModel.FK_SYSTEM_U_REFERENCE_SYSTEM_U", "System_User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChangingMajorsManagementSystemModel", Name="User_ChangingMajors_Start")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User_ChangingMajors_Start : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 User_ChangingMajors_Start 对象。
        /// </summary>
        /// <param name="start_id">start_id 属性的初始值。</param>
        public static User_ChangingMajors_Start CreateUser_ChangingMajors_Start(global::System.Int32 start_id)
        {
            User_ChangingMajors_Start user_ChangingMajors_Start = new User_ChangingMajors_Start();
            user_ChangingMajors_Start.start_id = start_id;
            return user_ChangingMajors_Start;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 start_id
        {
            get
            {
                return _start_id;
            }
            set
            {
                if (_start_id != value)
                {
                    Onstart_idChanging(value);
                    ReportPropertyChanging("start_id");
                    _start_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("start_id");
                    Onstart_idChanged();
                }
            }
        }
        private global::System.Int32 _start_id;
        partial void Onstart_idChanging(global::System.Int32 value);
        partial void Onstart_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String start_date
        {
            get
            {
                return _start_date;
            }
            set
            {
                Onstart_dateChanging(value);
                ReportPropertyChanging("start_date");
                _start_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("start_date");
                Onstart_dateChanged();
            }
        }
        private global::System.String _start_date;
        partial void Onstart_dateChanging(global::System.String value);
        partial void Onstart_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> start_flag
        {
            get
            {
                return _start_flag;
            }
            set
            {
                Onstart_flagChanging(value);
                ReportPropertyChanging("start_flag");
                _start_flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_flag");
                Onstart_flagChanged();
            }
        }
        private Nullable<global::System.Int32> _start_flag;
        partial void Onstart_flagChanging(Nullable<global::System.Int32> value);
        partial void Onstart_flagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_num
        {
            get
            {
                return _user_num;
            }
            set
            {
                Onuser_numChanging(value);
                ReportPropertyChanging("user_num");
                _user_num = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_num");
                Onuser_numChanged();
            }
        }
        private global::System.String _user_num;
        partial void Onuser_numChanging(global::System.String value);
        partial void Onuser_numChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ChangingMajorsManagementSystemModel", "FK_USER_ENT_REFERENCE_USER_CHA", "User_Entry")]
        public EntityCollection<User_Entry> User_Entry
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User_Entry>("ChangingMajorsManagementSystemModel.FK_USER_ENT_REFERENCE_USER_CHA", "User_Entry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User_Entry>("ChangingMajorsManagementSystemModel.FK_USER_ENT_REFERENCE_USER_CHA", "User_Entry", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChangingMajorsManagementSystemModel", Name="User_Entry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User_Entry : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 User_Entry 对象。
        /// </summary>
        /// <param name="entry_id">entry_id 属性的初始值。</param>
        public static User_Entry CreateUser_Entry(global::System.Int32 entry_id)
        {
            User_Entry user_Entry = new User_Entry();
            user_Entry.entry_id = entry_id;
            return user_Entry;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 entry_id
        {
            get
            {
                return _entry_id;
            }
            set
            {
                if (_entry_id != value)
                {
                    Onentry_idChanging(value);
                    ReportPropertyChanging("entry_id");
                    _entry_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("entry_id");
                    Onentry_idChanged();
                }
            }
        }
        private global::System.Int32 _entry_id;
        partial void Onentry_idChanging(global::System.Int32 value);
        partial void Onentry_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> start_id
        {
            get
            {
                return _start_id;
            }
            set
            {
                Onstart_idChanging(value);
                ReportPropertyChanging("start_id");
                _start_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_id");
                Onstart_idChanged();
            }
        }
        private Nullable<global::System.Int32> _start_id;
        partial void Onstart_idChanging(Nullable<global::System.Int32> value);
        partial void Onstart_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user_num
        {
            get
            {
                return _user_num;
            }
            set
            {
                Onuser_numChanging(value);
                ReportPropertyChanging("user_num");
                _user_num = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user_num");
                Onuser_numChanged();
            }
        }
        private global::System.String _user_num;
        partial void Onuser_numChanging(global::System.String value);
        partial void Onuser_numChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String major_name
        {
            get
            {
                return _major_name;
            }
            set
            {
                Onmajor_nameChanging(value);
                ReportPropertyChanging("major_name");
                _major_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("major_name");
                Onmajor_nameChanged();
            }
        }
        private global::System.String _major_name;
        partial void Onmajor_nameChanging(global::System.String value);
        partial void Onmajor_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sys_major_name
        {
            get
            {
                return _sys_major_name;
            }
            set
            {
                Onsys_major_nameChanging(value);
                ReportPropertyChanging("sys_major_name");
                _sys_major_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sys_major_name");
                Onsys_major_nameChanged();
            }
        }
        private global::System.String _sys_major_name;
        partial void Onsys_major_nameChanging(global::System.String value);
        partial void Onsys_major_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> entry_state
        {
            get
            {
                return _entry_state;
            }
            set
            {
                Onentry_stateChanging(value);
                ReportPropertyChanging("entry_state");
                _entry_state = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("entry_state");
                Onentry_stateChanged();
            }
        }
        private Nullable<global::System.Int32> _entry_state;
        partial void Onentry_stateChanging(Nullable<global::System.Int32> value);
        partial void Onentry_stateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> entry_flag
        {
            get
            {
                return _entry_flag;
            }
            set
            {
                Onentry_flagChanging(value);
                ReportPropertyChanging("entry_flag");
                _entry_flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("entry_flag");
                Onentry_flagChanged();
            }
        }
        private Nullable<global::System.Int32> _entry_flag;
        partial void Onentry_flagChanging(Nullable<global::System.Int32> value);
        partial void Onentry_flagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String major_id
        {
            get
            {
                return _major_id;
            }
            set
            {
                Onmajor_idChanging(value);
                ReportPropertyChanging("major_id");
                _major_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("major_id");
                Onmajor_idChanged();
            }
        }
        private global::System.String _major_id;
        partial void Onmajor_idChanging(global::System.String value);
        partial void Onmajor_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sys_major_id
        {
            get
            {
                return _sys_major_id;
            }
            set
            {
                Onsys_major_idChanging(value);
                ReportPropertyChanging("sys_major_id");
                _sys_major_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sys_major_id");
                Onsys_major_idChanged();
            }
        }
        private global::System.String _sys_major_id;
        partial void Onsys_major_idChanging(global::System.String value);
        partial void Onsys_major_idChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ChangingMajorsManagementSystemModel", "FK_USER_ENT_REFERENCE_USER_CHA", "User_ChangingMajors_Start")]
        public User_ChangingMajors_Start User_ChangingMajors_Start
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_ChangingMajors_Start>("ChangingMajorsManagementSystemModel.FK_USER_ENT_REFERENCE_USER_CHA", "User_ChangingMajors_Start").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_ChangingMajors_Start>("ChangingMajorsManagementSystemModel.FK_USER_ENT_REFERENCE_USER_CHA", "User_ChangingMajors_Start").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User_ChangingMajors_Start> User_ChangingMajors_StartReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User_ChangingMajors_Start>("ChangingMajorsManagementSystemModel.FK_USER_ENT_REFERENCE_USER_CHA", "User_ChangingMajors_Start");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User_ChangingMajors_Start>("ChangingMajorsManagementSystemModel.FK_USER_ENT_REFERENCE_USER_CHA", "User_ChangingMajors_Start", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ChangingMajorsManagementSystemModel", Name="User_Notice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User_Notice : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 User_Notice 对象。
        /// </summary>
        /// <param name="notice_id">notice_id 属性的初始值。</param>
        public static User_Notice CreateUser_Notice(global::System.Int32 notice_id)
        {
            User_Notice user_Notice = new User_Notice();
            user_Notice.notice_id = notice_id;
            return user_Notice;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 notice_id
        {
            get
            {
                return _notice_id;
            }
            set
            {
                if (_notice_id != value)
                {
                    Onnotice_idChanging(value);
                    ReportPropertyChanging("notice_id");
                    _notice_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("notice_id");
                    Onnotice_idChanged();
                }
            }
        }
        private global::System.Int32 _notice_id;
        partial void Onnotice_idChanging(global::System.Int32 value);
        partial void Onnotice_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notice_title
        {
            get
            {
                return _notice_title;
            }
            set
            {
                Onnotice_titleChanging(value);
                ReportPropertyChanging("notice_title");
                _notice_title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notice_title");
                Onnotice_titleChanged();
            }
        }
        private global::System.String _notice_title;
        partial void Onnotice_titleChanging(global::System.String value);
        partial void Onnotice_titleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notice_detail
        {
            get
            {
                return _notice_detail;
            }
            set
            {
                Onnotice_detailChanging(value);
                ReportPropertyChanging("notice_detail");
                _notice_detail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notice_detail");
                Onnotice_detailChanged();
            }
        }
        private global::System.String _notice_detail;
        partial void Onnotice_detailChanging(global::System.String value);
        partial void Onnotice_detailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notice_date
        {
            get
            {
                return _notice_date;
            }
            set
            {
                Onnotice_dateChanging(value);
                ReportPropertyChanging("notice_date");
                _notice_date = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notice_date");
                Onnotice_dateChanged();
            }
        }
        private global::System.String _notice_date;
        partial void Onnotice_dateChanging(global::System.String value);
        partial void Onnotice_dateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> notice_flag
        {
            get
            {
                return _notice_flag;
            }
            set
            {
                Onnotice_flagChanging(value);
                ReportPropertyChanging("notice_flag");
                _notice_flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("notice_flag");
                Onnotice_flagChanged();
            }
        }
        private Nullable<global::System.Int32> _notice_flag;
        partial void Onnotice_flagChanging(Nullable<global::System.Int32> value);
        partial void Onnotice_flagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notice_file
        {
            get
            {
                return _notice_file;
            }
            set
            {
                Onnotice_fileChanging(value);
                ReportPropertyChanging("notice_file");
                _notice_file = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notice_file");
                Onnotice_fileChanged();
            }
        }
        private global::System.String _notice_file;
        partial void Onnotice_fileChanging(global::System.String value);
        partial void Onnotice_fileChanged();

        #endregion

    
    }

    #endregion

    
}
